version: "2.3"
services:
  backend:
    build: ./backend
    environment:
      PORT: 3030
      SMTP_PORT: 2525
      HOST: https://mailer.webuxlab.com
    ports:
      - "3030"
      - "2525"
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-k",
          "-H",
          "Origin: https://mailer.webuxlab.com",
          "http://localhost:3030/api/v1/healthcheck",
        ]
      interval: 120s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./frontend
    environment:
      VUE_APP_IO_URL: "https://mailer.webuxlab.com/"
      SERVER_NAME: mailer.webuxlab.com
    ports:
      - "80"
      - "443"
    volumes:
      - "/srv/JAFSS/nginx/logs/:/var/log/nginx/"
    restart: always
    links:
      - backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 120s
      timeout: 10s
      retries: 5
