version: "2.3"
services:
  backend:
    # build: ./backend
    image: mailer-backend:latest
    environment:
      PORT: 3030
      SMTP_PORT: 2525
      HOST: https://mailer.webuxlab.com
    ports:
      - "2525:2525"
    restart: always
    network_mode: bridge # Nginx jwilder
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-k",
          "-H",
          "Origin: https://mailer.webuxlab.com",
          "http://localhost:3030/healthcheck",
        ]
      interval: 120s
      timeout: 10s
      retries: 5

  frontend:
    # build:
    #   context: ./frontend
    image: mailer-frontend:latest
    environment:
      SERVER_NAME: mailer.webuxlab.com
      VIRTUAL_HOST: mailer.webuxlab.com # Nginx jwilder
      LETSENCRYPT_HOST: mailer.webuxlab.com # Nginx jwilder
    # ports:
    #   - "80"
    #   - "443"
    volumes:
      - "/srv/JAFSS/nginx/logs/:/var/log/nginx/"
    restart: always
    links:
      - backend
    network_mode: bridge # Nginx jwilder
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 120s
      timeout: 10s
      retries: 5
